includes:
- configs/is2re/all/base.yml

model:
  name: cgcnn-evidential
  evidential: True
  atom_embedding_size: 384
  fc_feat_size: 512
  num_fc_layers: 4
  num_graph_conv_layers: 6
  num_gaussians: 100
  cutoff: 6.0
  regress_forces: False
  use_pbc: True
  lambda_: 0.05
  units: 1
  softplus_beta: 1
  softplus_threshold: 20

# *** Important note ***
#   The total number of gpus used for this run was 1.
#   If the global batch size (num_gpus * batch_size) is modified
#   the lr_milestones and warmup_steps need to be adjusted accordingly.

optim:
  batch_size: 16
  eval_batch_size: 16
  num_workers: 16
  lr_initial: 0.001
  lr_gamma: 0.1
  lr_milestones: # steps at which lr_initial <- lr_initial * lr_gamma
    - 17981
    - 32366
    - 46752
  warmup_steps: 10788
  warmup_factor: 0.2
  max_epochs: 10
  loss_energy: evidential

dataset:
  # train data
  - src: /pscratch/sd/v/varunvm/ocp/data/is2re/all/train/data.lmdb
    normalize_labels: True
    target_mean: -1.525913953781128
    target_std: 2.279365062713623
  # val data (optional)
  - src: /pscratch/sd/v/varunvm/ocp/data/is2re/all/val_id/data.lmdb
  # test data (optional)
  - src: /pscratch/sd/v/varunvm/ocp/data/is2re/all/val_id/data.lmdb

task:
  exp_task_name: IS2RE
  exp_desc: Val ID Prediction
  exp_data_size: all
  exp_model: CGCNN Evidential
